version: '2'

services:

  wordpress-backup:
    image: wordpress
    restart: always
    ports:
      - 8090:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: rolf_user_db 
      WORDPRESS_DB_PASSWORD: 1234
      WORDPRESS_DB_NAME: wordpress_db
    volumes:
      - wordpress-backup:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: rolf_user_db
      MYSQL_PASSWORD: 1234
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db-backup:/var/lib/mysql

volumes:
  wordpress-backup:
  db-backup:
